markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1

repository: https://github.com/dedalozzo/www.elephantoncouch.com

collections:
  tutorial
    output: true